name: CI

on:
  push:
    branches-ignore:
      - main
      - dev-branch
      - qa-branch

jobs:
  build:
    name: Build (backend only)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Remove legacy yarnPath so setup-node doesn't choke
      - name: Remove yarnPath override (if present)
        run: |
          if [ -f .yarnrc.yml ]; then
            sed -i '/^yarnPath:/d' .yarnrc.yml
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack + Yarn 4.10.3
        run: |
          corepack enable
          corepack prepare yarn@4.10.3 --activate
          yarn -v

      - name: Prepare Yarn cache dir
        run: mkdir -p .yarn/cache

      - name: Cache Yarn artifacts
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn4-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn4-

      - name: Install deps
        run: yarn install --immutable

      - name: Build (only if script exists)
        run: |
          if yarn run | grep -qE '(^|[[:space:]])build($|[[:space:]])'; then
            yarn build
          else
            echo "No build script found, skipping."
          fi