# name: CI & Deploy (Lightsail + PM2)

# on:
#   push:
#     branches: ["**"]
#   workflow_dispatch:
#     inputs:
#       branch:
#         description: "Branch to deploy (default: main)"
#         required: false
#         default: "main"

# jobs:
#   build:
#     name: Build (backend only)
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       # Remove legacy yarnPath so setup-node doesn’t choke
#       - name: Remove yarnPath override (if present)
#         run: |
#           if [ -f .yarnrc.yml ]; then
#             sed -i '/^yarnPath:/d' .yarnrc.yml
#           fi

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Enable Corepack + Yarn 4.10.3
#         run: |
#           corepack enable
#           corepack prepare yarn@4.10.3 --activate
#           yarn -v

#       - name: Prepare Yarn cache dir
#         run: mkdir -p .yarn/cache

#       - name: Cache Yarn artifacts
#         uses: actions/cache@v4
#         with:
#           path: .yarn/cache
#           key: ${{ runner.os }}-yarn4-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn4-

#       - name: Install deps
#         run: yarn install --immutable

#       - name: Build (only if script exists)
#         run: |
#           if yarn run | grep -qE '(^|[[:space:]])build($|[[:space:]])'; then
#             yarn build
#           else
#             echo "No build script found, skipping."
#           fi

#   deploy:
#     name: Deploy to Lightsail (PM2)
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
#     steps:
#       - name: Select branch (manual runs can override)
#         id: sel
#         run: |
#           if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
#             echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
#           else
#             echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
#           fi

#       - name: Deploy over SSH (git pull + install/build + PM2 reload)
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.LIGHTSAIL_HOST }}
#           username: ${{ secrets.LIGHTSAIL_USER }}
#           port: ${{ secrets.SSH_PORT || 22 }}
#           key: ${{ secrets.LIGHTSAIL_KEY }}
#           script_stop: true
#           script: |

- name: Test SSH connectivity
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.LIGHTSAIL_HOST }}
    username: ${{ secrets.LIGHTSAIL_USER }}
    key: ${{ secrets.LIGHTSAIL_KEY }}
    port: 22
    fingerprint: "SHA256:zi9nWtN/3L++kd0JsCmNlXmPHVeOtW5Ug/zA/qMuSlo"
    debug: true
    script_stop: true
    script: |
      whoami
      uname -a
      echo "✅ SSH works"
