name: CI / Deploy Backend to Lightsail

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: |
          corepack enable
          corepack prepare yarn@4.10.3 --activate
          yarn -v
      - run: yarn install --immutable
      - run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_KEY }}
      - run: ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts
      - run: |
          ssh ubuntu@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            set -euo pipefail
            APP_ROOT="/var/www/app"

            sudo mkdir -p "$APP_ROOT"
            sudo chown -R ubuntu:ubuntu "$APP_ROOT"
            cd "$APP_ROOT"

            if [ ! -d ".git" ]; then
              git clone https://github.com/${GITHUB_REPOSITORY}.git .
            else
              git fetch --all
              git reset --hard origin/main
            fi

            corepack enable || true
            corepack prepare yarn@4.10.3 --activate
            yarn -v

            yarn install --immutable
            yarn build

            pm2 start ecosystem.config.js --only backend --update-env || true
            pm2 restart backend --update-env || true
            pm2 save
          EOF
