name: CI & Deploy (Lightsail + PM2)

on:
  push:
    branches: ["**"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy (default: main)"
        required: false
        default: "main"

jobs:
  build:
    name: Build (root project)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Strip legacy Yarn configs before we ever run yarn
      - name: Sanitize Yarn config (remove legacy v1 settings)
        run: |
          # remove legacy .yarnrc (Yarn v1)
          [ -f .yarnrc ] && rm -f .yarnrc

          # remove yarnPath if present (we're using Corepack-managed Yarn)
          [ -f .yarnrc.yml ] && sed -i '/^yarnPath:/d' .yarnrc.yml

          # fix or drop legacy cacheDir key (Yarn 4 uses cacheFolder)
          if [ -f .yarnrc.yml ]; then
            if grep -q '^cacheDir:' .yarnrc.yml; then
              # convert to cacheFolder
              sed -i 's/^cacheDir:/cacheFolder:/' .yarnrc.yml
            fi
          fi

      - name: Enable Corepack + pin Yarn 4.10.3
        run: |
          corepack enable
          corepack prepare yarn@4.10.3 --activate
          yarn --version

      # Cache Yarn's actual cache folder (Yarn 4 default is global cache)
      - name: Discover Yarn cache dir
        id: yarncache
        run: echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> "$GITHUB_ENV"

      - name: Cache Yarn artifacts
        uses: actions/cache@v4
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarncache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarncache-

      - name: Install deps
        run: yarn install --immutable

      - name: Build (only if script exists)
        run: |
          if yarn run | grep -qE '(^|[[:space:]])build($|[[:space:]])'; then
            yarn build
          else
            echo "No build script found, skipping."
          fi

  deploy:
    name: Deploy to Lightsail (PM2)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Select branch (manual runs can override)
        id: sel
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy over SSH (git pull + install/build + PM2 reload)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          port: ${{ secrets.SSH_PORT || 22 }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script_stop: true
          script: |
            set -e
            APP_DIR=${{ secrets.APP_DIR }}   # e.g. /var/www/app/reactflowbackend
            cd "$APP_DIR"

            # Update code to target branch
            if [ -d .git ]; then
              git fetch --all --prune
              git checkout "${{ steps.sel.outputs.BRANCH }}"
              git reset --hard "origin/${{ steps.sel.outputs.BRANCH }}"
            else
              echo "Directory is not a git repo. Please clone repo into $APP_DIR first."
              exit 1
            fi

            # Sanitize Yarn config on server too
            [ -f .yarnrc ] && rm -f .yarnrc || true
            if [ -f .yarnrc.yml ]; then
              sed -i '/^yarnPath:/d' .yarnrc.yml || true
              if grep -q '^cacheDir:' .yarnrc.yml; then
                sed -i 's/^cacheDir:/cacheFolder:/' .yarnrc.yml || true
              fi
            fi

            # Ensure Corepack/Yarn
            if command -v corepack >/dev/null 2>&1; then
              corepack enable
              corepack prepare yarn@4.10.3 --activate
            else
              echo "corepack not found. Install Node 18+/20+ or enable Corepack."
              exit 1
            fi

            yarn install --immutable

            if yarn run | grep -qE '(^|[[:space:]])build($|[[:space:]])'; then
              yarn build
            else
              echo "No build script found, skipping."
            fi

            pm2 startOrReload ecosystem.config.js
            pm2 save
            pm2 ls
