name: CI & Deploy (Lightsail + PM2)

on:
  push:
    branches: ["**"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy (default: main)"
        required: false
        default: "main"

jobs:
  build:
    name: Build (backend only)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # don't use cache: yarn (causes early yarn call)

      - name: Remove yarnPath override (if present)
        run: |
          if [ -f .yarnrc.yml ]; then
            sed -i '/^yarnPath:/d' .yarnrc.yml
          fi

      - name: Enable Corepack + Yarn 4.10.3
        run: |
          corepack enable
          corepack prepare yarn@4.10.3 --activate
          yarn --version

      - name: Cache Yarn artifacts
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarncache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarncache-

      - name: Install deps (root) - optional
        run: |
          if [ -f package.json ]; then
            yarn install --immutable
          fi

      - name: Install & build backend
        run: |
          if [ -f backend/package.json ]; then
            cd backend
            yarn install --immutable
            if yarn run | grep -qE '(^|[[:space:]])build($|[[:space:]])'; then
              yarn build
            fi
          fi

  deploy:
    name: Deploy to Lightsail (PM2)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Select branch (manual runs can override)
        id: sel
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy over SSH (git pull + backend build + PM2 reload)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script_stop: true
          script: |
            set -e
            APP_DIR=${{ secrets.APP_DIR }}   # e.g. /var/www/app
            cd "$APP_DIR"

            # Update code
            if [ -d .git ]; then
              git fetch --all --prune
              git checkout "${{ steps.sel.outputs.BRANCH }}"
              git reset --hard "origin/${{ steps.sel.outputs.BRANCH }}"
            else
              echo "Directory is not a git repo. Please clone repo into $APP_DIR first."
              exit 1
            fi

            # Remove yarnPath override if exists
            if [ -f .yarnrc.yml ]; then
              sed -i '/^yarnPath:/d' .yarnrc.yml || true
            fi

            # Enable Corepack + Yarn 4.10.3
            if command -v corepack >/dev/null 2>&1; then
              corepack enable
              corepack prepare yarn@4.10.3 --activate
            fi

            # Root install
            if [ -f package.json ]; then
              yarn install --immutable
            fi

            # Backend install & build
            if [ -f backend/package.json ]; then
              cd backend
              yarn install --immutable
              if yarn run | grep -qE '(^|[[:space:]])build($|[[:space:]])'; then
                yarn build
              fi
              cd ..
            fi

            # Reload PM2
            pm2 startOrReload ecosystem.config.js
            pm2 save
            pm2 ls
