name: SSH test (Lightsail)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connectivity
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}        # e.g. 3.129.39.38
          username: ${{ secrets.LIGHTSAIL_USER }}     # ubuntu
          key: ${{ secrets.LIGHTSAIL_KEY }}           # PEM contents
          port: 22
          fingerprint: "SHA256:zi9nWtN/3L++kd0JsCmNlXmPHVeOtW5Ug/zA/qMuSlo"
          debug: true
          script_stop: true
          script: |
            whoami
            uname -a
            echo "✅ SSH works"
