name: CI & Deploy (Lightsail + PM2)

on:
  push:
    branches: ["**"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy (default: main)"
        required: false
        default: "main"

jobs:
  build:
    name: Build (backend only)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Move yarnPath removal BEFORE setup-node to avoid the early error
      - name: Remove yarnPath override (if present)
        run: |
          if [ -f .yarnrc.yml ]; then
            sed -i '/^yarnPath:/d' .yarnrc.yml
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack + pin Yarn 4.10.3 for this run
        run: |
          corepack enable
          corepack prepare yarn@4.10.3 --activate
          yarn --version

      - name: Discover Yarn cache dir
        id: yarncache
        run: echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> "$GITHUB_ENV"

      - name: Ensure cache dir exists (prevents save warning)
        run: mkdir -p "${{ env.YARN_CACHE_DIR }}"

      - name: Cache Yarn artifacts
        uses: actions/cache@v4
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarncache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarncache-

      # Backend-only repo install & build
      - name: Install deps
        run: yarn install --immutable

      - name: Build (only if script exists)
        run: |
          if yarn run | grep -qE '(^|[[:space:]])build($|[[:space:]])'; then
            yarn build
          else
            echo "No build script found, skipping."
          fi

  deploy:
    name: Deploy to Lightsail (PM2)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Select branch (manual runs can override)
        id: sel
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy over SSH (git pull + install/build + PM2 reload)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          port: ${{ secrets.SSH_PORT || 22 }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script_stop: true
          script: |
            set -e
            APP_DIR=${{ secrets.APP_DIR }}
            cd "$APP_DIR"

            if [ -d .git ]; then
              git fetch --all --prune
              git checkout "${{ steps.sel.outputs.BRANCH }}"
              git reset --hard "origin/${{ steps.sel.outputs.BRANCH }}"
            else
              echo "Directory is not a git repo. Please clone repo into $APP_DIR first."
              exit 1
            fi

            # If you later pin Yarn in repo (.yarn/releases), remove the next sed line
            if [ -f .yarnrc.yml ]; then
              sed -i '/^yarnPath:/d' .yarnrc.yml || true
            fi

            corepack enable
            corepack prepare yarn@4.10.3 --activate
            yarn -v

            yarn install --immutable

            if yarn run | grep -qE '(^|[[:space:]])build($|[[:space:]])'; then
              yarn build
            else
              echo "No build script found, skipping."
            fi

            pm2 startOrReload ecosystem.config.js
            pm2 save
            pm2 ls
